<section id="political" class="section" style="background:#f0f9f6">
<div class="container">
<div class="section-header fade-in">
<span style="color:var(--primary);font-weight:700;letter-spacing:1px">রাজনৈতিক পরিচয়</span>
<h2>এক দশকেরও বেশি সময় রাজপথে জনতার সেবায়</h2>
<div class="divider"></div>
</div>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:25px">
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">👥</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সাবেক যুগ্ম সাধারণ সম্পাদক</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">জগন্নাথ বিশ্ববিদ্যালয় ছাত্রদল (২০২২-২৫)</div></div></div>
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">🛡️</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সাবেক সহ-সভাপতি</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">সাতক্ষীরা জেলা ছাত্রদল (২০১৬-২২)</div></div></div>
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">🏅</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সাবেক ভারপ্রাপ্ত সভাপতি</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">খেশরা ইউনিয়ন ছাত্রদল (২০১০-১৪)</div></div></div>
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">👥</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সদস্য (আহ্বায়ক কমিটি)</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">তালা উপজেলা যুবদল</div></div></div>
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">💼</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সাবেক সাধারণ সম্পাদক</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">ঢাকাস্থ তালা উপজেলা জাতীয়তাবাদী ছাত্র ফোরাম (২০১২-১৪)</div></div></div>
<div class="fade-in" style="padding:25px;background:#fff;border-radius:20px;box-shadow:var(--shadow);border:1px solid var(--glass-border);display:flex;gap:20px;align-items:center"><div style="min-width:55px;height:55px;background:rgba(244,42,65,0.1);border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.5rem">🏆</div><div><div style="font-weight:800;color:var(--primary-dark);font-size:1.1rem">সাধারণ সম্পাদক</div><div style="color:var(--text-muted);font-size:0.9rem;margin-top:5px">এইচ এম এস স্পোর্টিং ক্লাব (২০২৪ - চলমান)</div></div></div>
</div>
<div class="fade-in" style="margin-top:50px;text-align:center"><p style="max-width:800px;margin:0 auto;color:var(--text-muted);font-size:1.1rem">এছাড়াও তিনি বিভিন্ন ধর্মীয় ও সামাজিক প্রতিষ্ঠানের আজীবন সদস্য ও দাতা সদস্য হিসেবে নিরলসভাবে কাজ করে যাচ্ছেন।</p></div>
</div>
</section>