<section id="social" class="section">
<div class="container">
<div class="section-header fade-in"><span style="color:var(--primary);font-weight:700;letter-spacing:1px">সমাজসেবা</span><h2>আমাদের পথচলা, মানুষের কল্যাণে</h2><div class="divider"></div></div>
<div class="social-grid">
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=600&auto=format&fit=crop" alt="শীতার্ত"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">❤️</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">শীতার্ত মানুষের পাশে</h3><p style="color:var(--text-muted);font-size:0.95rem">প্রতি বছর কয়েক হাজার অসহায় মানুষের মাঝে কম্বল ও শীতবস্ত্র বিতরণ।</p></div></div>
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?q=80&w=600&auto=format&fit=crop" alt="শিক্ষা"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">🎓</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">শিক্ষা সহায়তা</h3><p style="color:var(--text-muted);font-size:0.95rem">অভাবী মেধাবী শিক্ষার্থীদের ভর্তি ও উচ্চশিক্ষায় নিয়মিত আর্থিক সহযোগিতা।</p></div></div>
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?q=80&w=600&auto=format&fit=crop" alt="মাদক"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">🛡️</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">মাদক ও জুয়া বিরোধী সচেতনতা</h3><p style="color:var(--text-muted);font-size:0.95rem">তরুণ সমাজকে রক্ষায় নিয়মিত মাদক ও অনলাইন জুয়া বিরোধী সচেতনতামূলক সভা।</p></div></div>
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="<?php echo plugin_dir_url(__FILE__) . '../assets/images/ক্রীড়া সামগ্রী বিতরণ.jpeg'; ?>" alt="ক্রীড়া"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">🏆</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">ক্রীড়া সামগ্রী বিতরণ</h3><p style="color:var(--text-muted);font-size:0.95rem">এলাকার ক্লাব ও শিক্ষা প্রতিষ্ঠানে ফুটবল, ক্রিকেট ও জার্সি বিতরণ।</p></div></div>
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=600&auto=format&fit=crop" alt="চিকিৎসা"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">🏥</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">সুচিকিৎসা নিশ্চিতকরণ</h3><p style="color:var(--text-muted);font-size:0.95rem">জরুরি চিকিৎসা ও হাসপাতালে সুচিকিৎসার নিশ্চয়তায় সার্বক্ষণিক সহায়তা।</p></div></div>
<div class="social-card fade-in"><div style="position:relative"><img class="social-card-img" src="https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=600&auto=format&fit=crop" alt="কৃষি"><div style="position:absolute;bottom:-20px;right:20px;width:50px;height:50px;background:var(--primary);color:#fff;border-radius:15px;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow)">🌱</div></div><div class="social-card-content" style="padding-top:35px"><h3 style="margin-bottom:10px;font-size:1.2rem;color:var(--primary-dark)">কৃষি ও পরিবেশ উন্নয়ন</h3><p style="color:var(--text-muted);font-size:0.95rem">পরিবেশ রক্ষায় বৃক্ষরোপণ এবং কৃষকদের কৃষি বিষয়ক পরামর্শ ও সহায়তা।</p></div></div>
</div>
</div>
</section>