<section id="videos" class="section" style="background:#f0f9f6">
<div class="container">
<div class="section-header fade-in"><span style="color:var(--primary);font-weight:700;letter-spacing:1px">ভিডিও গ্যালারি</span><h2>বক্তব্য ও কার্যক্রম</h2><div class="divider"></div></div>
<div class="video-grid">
<div class="video-card fade-in" data-embed="https://www.youtube.com/embed/ScMzIvxBSi4" data-title="মাদক বিরোধী সমাবেশ ও বক্তব্য"><div class="video-thumb"><img src="/assets/speech.png" alt="Speech"><div class="play-btn">▶</div></div><div class="video-info"><div style="color:var(--primary);font-size:0.8rem;font-weight:700;margin-bottom:5px;text-transform:uppercase">Speech Video</div><h3 style="font-size:1.1rem;color:var(--primary-dark)">মাদক বিরোধী সমাবেশ ও বক্তব্য</h3></div></div>
<div class="video-card fade-in" data-embed="https://www.youtube.com/embed/aqz-KE-bpKQ" data-title="উদ্যোক্তা হিসেবে পথচলা"><div class="video-thumb"><img src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop" alt="Entrepreneur"><div class="play-btn">▶</div></div><div class="video-info"><div style="color:var(--primary);font-size:0.8rem;font-weight:700;margin-bottom:5px;text-transform:uppercase">Entrepreneur Video</div><h3 style="font-size:1.1rem;color:var(--primary-dark)">উদ্যোক্তা হিসেবে পথচলা</h3></div></div>
<div class="video-card fade-in" data-embed="https://www.youtube.com/embed/ysz5S6PUM-U" data-title="সংকট মুহূর্তে মানুষের পাশে"><div class="video-thumb"><img src="https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?q=80&w=600&auto=format&fit=crop" alt="Crisis"><div class="play-btn">▶</div></div><div class="video-info"><div style="color:var(--primary);font-size:0.8rem;font-weight:700;margin-bottom:5px;text-transform:uppercase">Crisis Moment</div><h3 style="font-size:1.1rem;color:var(--primary-dark)">সংকট মুহূর্তে মানুষের পাশে</h3></div></div>
<div class="video-card fade-in" data-embed="https://www.youtube.com/embed/jNQXAC9IVRw" data-title="নেতৃত্ব ও ভবিষ্যৎ পরিকল্পনা"><div class="video-thumb"><img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=600&auto=format&fit=crop" alt="Leadership"><div class="play-btn">▶</div></div><div class="video-info"><div style="color:var(--primary);font-size:0.8rem;font-weight:700;margin-bottom:5px;text-transform:uppercase">Leadership Video</div><h3 style="font-size:1.1rem;color:var(--primary-dark)">নেতৃত্ব ও ভবিষ্যৎ পরিকল্পনা</h3></div></div>
</div>
</div>
</section>